prjKUST/Controllers/AdminIndexController.cs
using prjKUST.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TVMLib.Controllers;

namespace prjKUST.Controllers
{
    [AuthorizeAdminFilter]
    public class AdminIndexController : BaseController
    {
        // GET: AdminIndex
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            this.ControllerContext.HttpContext.Session.RemoveAll();
            var l_Cookie = new HttpCookie(FormsAuthentication.FormsCookieName)
            {
                Expires = DateTime.Now.AddDays(-1),
                HttpOnly = true
            };
            Response.Cookies.Add(l_Cookie);
            SetResultMessage("登出成功");
            return RedirectToAction("AdminLogin", "AdminLogin");
        }
    }
}

prjKUST/Controllers/MemberController.cs
using prjKUST.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVMLib;
using TVMLib.Controllers;
using TVMLib.dl;
using TVMLib.dl.Login;

namespace prjKUST.Controllers
{
    public class MemberController : BaseController
    {
        // GET: Member
        public ActionResult Login(string p_PRODUCT_GUID = "")
        {
            ViewBag.PRODUCT_GUID = p_PRODUCT_GUID;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SkipAuthorizeFilterAttribute]
        public ActionResult Login(LoginVM p_Data,string p_PRODUCT_GUID="")
        {
            if (ModelState.IsValidField("ACCOUNT") && ModelState.IsValidField("PASSWORD"))
            {
                TB_USER l_TB_USER = _PageContext.ServiceManager.TB_USERService.SearchByAccAndPwd(p_Data.ACCOUNT, p_Data.PASSWORD);
                if (l_TB_USER != null)
                {
                    //登入成功
                    Utility.GenLoginUserCookieAndSessionInfo(l_TB_USER);

                    SetResultMessage("使用者：" + l_TB_USER.NAME + "登入成功");

                    //有PRODUCT_GUID = 從 商品明細頁 沒有登入 進來的 所以導回去
                    if (p_PRODUCT_GUID != "")
                    {
                        return RedirectToAction("ProductDetail", "Product",new { p_RRODUCT_GUID  = p_PRODUCT_GUID });
                    }
                    else {
                        return RedirectToAction("Index", "Index");
                    }
                }
                else
                {
                    SetResultMessage("帳號或密碼有誤，請重新確認。");
                }
            }

            SetResultMessage("帳號或密碼有誤，請確認。");
            return View(p_Data);
        }
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SkipAuthorizeFilterAttribute]
        public ActionResult Register(RegisteredVM p_Data)
        {
            if (ModelState.IsValid)
            {

                TB_USER l_TB_USER = new TB_USER();
                l_TB_USER.NAME = p_Data.NAME;
                l_TB_USER.ACCOUNT = p_Data.ACCOUNT;
                l_TB_USER.PASSWORD = p_Data.PASSWORD;
                l_TB_USER.EMAIL = p_Data.EMAIL;
                l_TB_USER.ADDRESS = p_Data.ADDRESS;
                l_TB_USER.AREA = p_Data.AREA;
                l_TB_USER.CITY = p_Data.CITY;
                l_TB_USER.ZIP = p_Data.ZIP;
                l_TB_USER.IS_ACTIVE = true;
                l_TB_USER.IS_ADMIN = false;
                l_TB_USER.TEL = p_Data.TEL;
                l_TB_USER.USER_GUID = Guid.NewGuid().ToString();
                l_TB_USER.CREATE_TIME = DateTime.Now;

                l_TB_USER.CREATE_USER = l_TB_USER.USER_GUID;
                l_TB_USER.EDIT_TIME = DateTime.Now;
                l_TB_USER.EDIT_USER = l_TB_USER.USER_GUID;



                _PageContext.ServiceManager.TB_USERService.Create(l_TB_USER);
                SetResultMessage("會員：" + p_Data.NAME + " 註冊成功。");
                return RedirectToAction("Login");
            }
            SetResultMessage("註冊失敗，請確認資料內容");
            return Register(p_Data);
        }


        public ActionResult Forget()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SkipAuthorizeFilterAttribute]
        public ActionResult Forget(ForgetVM p_Data)
        {
            if (ModelState.IsValidField("EMAIL"))
            {
                if (_PageContext.ServiceManager.TB_USERService.GetNewPwdByEmail(p_Data.EMAIL))
                    SetResultMessage("已發送新密碼至您的信箱！");
                else
                    SetResultMessage("發送新密碼至您的信箱時失敗，請聯絡系統管理員！");

                return View();
            }
            else
            {
                SetResultMessage("輸入資料有誤，請確認。");
                return View(p_Data);
            }
          
        }
    }
}

prjKUST/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/aseets_admin/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/aseets_admin/css/footable.bootstrap.min.css" rel="stylesheet" />
    <link href="~/aseets_admin/css/master.min.css" rel="stylesheet" />

    <script src="~/aseets_admin/js/jquery.min.js"></script>
    <script src="~/aseets_admin/js/bootstrap.min.js"></script>
    <script src="~/aseets_admin/js/footable.min.js"></script>
    <script src="~/aseets_admin/js/jquery.twzipcode.min.js"></script>
</head>
<body>
    <div class="header">
        <div class="top-wrap common-wrap">
            <div class="side-menu-btn">
                <span></span>
            </div>
            <a href="@Url.Action("Index","adminindex")" class="logo-wrap">
                <img src="~/aseets_admin/img/雄大科技logo1.png" />
            </a>
            @if (@TVMLib.Utility.UserData.USER_GUID != null)
            {
                <div class="link-wrap">
                    <span class="hidden-for-mobile">
                        <text>您好，@TVMLib.Utility.UserData.NAME</text>
                        &nbsp;&nbsp;|
                        <a href="@Url.Action("Logout", "AdminIndex")">登出</a>
                    </span>
                </div>
            }

        </div>

        <div class="menu-wrap">
            @if (@TVMLib.Utility.UserData.USER_GUID != null)
            {
                <div class="common-wrap">

                    <div class="show-for-mobile">
                        <a href="@Url.Action("Logout", "AdminIndex")">您好，系統管理者 | 登出</a>
                    </div>
                    @*<a href="@Url.Action("AdminSlider", "AdminSlider")">輪播管理</a>*@
                    <a href="@Url.Action("AdminAboutus", "AdminAboutus")">關於我們</a>
                    <a href="@Url.Action("AdminNews", "AdminNews")">消息管理</a>
                    <a href="@Url.Action("AdminProCategory", "AdminProCategory")">產品類別</a>
                    <a href="@Url.Action("AdminProduct", "AdminProduct")">產品管理</a>
                    <a href="@Url.Action("AdminProfile", "AdminProfile")">技術規格</a>
                    <a href="@Url.Action("AdminQA", "AdminQA")">Q&A管理</a>
                    <a href="@Url.Action("AdminContact", "AdminContact")">聯絡我們</a>
                    <a href="@Url.Action("AdminMember", "AdminMember")">會員管理</a>
                    <a href="@Url.Action("AdminOrder", "AdminOrder")">訂單管理</a>
                    <a href="@Url.Action("AdminInquiry", "AdminInquiry")">詢價管理</a>
                </div>
            }
        </div>

    </div>


    <div>
        @RenderBody()
    </div>
    <div class="footer">
        © @System.DateTime.Now.Year KUST Innovative 雄大科技 , All Rights Reserved.
    </div>

    <div id="modal-container" class="modal fade hidden-print" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

            </div>
        </div>
    </div>
    @if (TempData[TVMLib.common.SealedGlobalPage.RESULT_MESSAGE] != null)
    {
        <div class="alert-box">
            @TempData[TVMLib.common.SealedGlobalPage.RESULT_MESSAGE]

            <style>
                .alert-box {
                    background-color: rgba(56, 128, 78, 0.8);
                    color: #FFF;
                    position: absolute;
                    left: 50%;
                    top: 0;
                    transform: translateX(-50%) translateY(-110%);
                    transition: all .8s;
                    padding: 30px 40px;
                    z-index: 99;
                    border-radius: 10px;
                    font-size: 0.9em;
                    box-shadow: 2px 2px 4px rgba(0,0,0,.15);
                    line-height: 175%;
                }

                    .alert-box.show {
                        top: 150px;
                        transform: translateX(-50%) translateY(0%);
                    }
            </style>

            <script>
                jQuery(function () {
                    $(".alert-box").addClass("show");
                    setTimeout(function () {
                        $('.alert-box').removeClass('show');
                    }, 6000);
                });
            </script>
        </div>
    }
    <script>

        $(".side-menu-btn").click(function () {
            $(".side-menu-btn").toggleClass("menu-open");
            $(".menu-wrap").toggleClass("menu-open");
        })

        jQuery(function ($) {
            $('.footable').footable();
        });


        $(function () {
            // boostrap 4 load modal example from docs

            $('#modal-container').on('show.bs.modal', function (event) {

                var button = $(event.relatedTarget); // Button that triggered the modal

                var url = button.attr("href");

                var modal = $(this);

                // note that this will replace the content of modal-content everytime the modal is opened
                modal.find('.modal-content').load(url);

            });

            $('#modal-container').on('hidden.bs.modal', function () {

                // remove the bs.modal data attribute from it

                $(this).removeData('bs.modal');

                // and empty the modal-content element

                $('#modal-container .modal-content').empty();

            });
        });

    </script>


</body>
</html>

prjKUST/Views/Shared/_ContentLayout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KUST Innovative 雄大科技</title>
    <meta name="description" content="">
    <meta name="author" content="">
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <!--favicon-->
    <link rel=icon href="~/assets/favicon/favicon-20200403023240123.ico" sizes="16x16" type="image/png">
    <!-- CSS -->
    <link href="~/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/simpletextrotator.css" rel="stylesheet">
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/assets/css/et-line-font.css" rel="stylesheet">
    <link href="~/assets/css/magnific-popup.css" rel="stylesheet">
    <link href="~/assets/css/flexslider.css" rel="stylesheet">
    <link href="~/assets/css/owl.carousel.css" rel="stylesheet">
    <link href="~/assets/css/animate.css" rel="stylesheet">
    <link href="~/assets/css/style.css" rel="stylesheet">




    <!-- Javascript files -->
    <script src="~/assets/js/jquery-2.1.3.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>

    <style>
        @@font-face {
            font-family: 'TaipeiSansTC';
            src: url('/fonts/TaipeiSansTCBeta-Regular.ttf');
            src: url('/fonts/TaipeiSansTCBeta-Bold.ttf');
        }

        body {
            font-family: 'TaipeiSansTC' !important;
        }

        .error-tip {
            color: red !important;
        }
    </style>
</head>
<body>


    <!-- Preloader -->
    <div class="page-loader">
        <div class="loader">Loading...</div>
    </div>

    <!-- Navigation start -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">

        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a style="width:110px;padding:10px 15px !important" class="navbar-brand" href="@Url.Action("Index", "Index")"><img src="~/images/雄大科技logo1.png" border="0"></a>
            </div>

            <div class="collapse navbar-collapse" id="custom-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li><a href="@Url.Action("Aboutus", "Aboutus")" class="section-scroll">公司介紹</a></li>
                    <li><a href="@Url.Action("News", "News")" class="section-scroll">最新消息</a></li>
                    @*<li><a href="@Url.Action("Hot", "Product")">熱銷產品</a></li>*@

                    <li class="dropdown">
                        <a href="@Url.Action("Product", "Product", new { p_Type = "ALL" })" class="dropdown-toggle section-scroll" data-toggle="dropdown">所有產品</a>   <ul class="dropdown-menu">
                            @if (ViewBag.PRODUCT_MENU != null)
                            {
                                foreach (var item in ViewBag.PRODUCT_MENU as List<TVMLib.dl.Index.MenuProductCategoryVM>)
                                {
                                    <li class="dropdown">
                                        <a href="@Url.Action("Product", "Product", new { p_Type = item.NAME, p_CATEGORY = item.CATEGORY_GUID })" class="dropdown-toggle" data-toggle="dropdown"> @item.NAME </a>
                                        <ul class="dropdown-menu">
                                            @if (item.l_MenuProductVM != null)
                                            {
                                                foreach (var detail in item.l_MenuProductVM)
                                                {
                                                    <li><a href="@detail.URL">@detail.NAME</a></li>
                                                }
                                            }

                                        </ul>
                                    </li>
                                }
                            }
                        </ul>
                    </li>

                    <li><a href="@Url.Action("Profile", "Profile")#totop">技術規格</a></li>
                    <li><a href="@Url.Action("QA", "QA")">Q & A</a></li>
                    <li><a href="@Url.Action("Index", "Index")#contact" class="section-scroll">連絡我們</a></li>

                    @if (!String.IsNullOrEmpty(TVMLib.Utility.UserData.USER_GUID))
                    {
                        <li><a href="#">您好，@TVMLib.Utility.UserData.NAME</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Login","Member")">會員登入/註冊</a></li>
                    }

                    <!-- CART -->
                    <li class="dropdown navbar-cart">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="icon-basket"></span>
                            <span class="cart-item-number">
                                @if (ViewBag.ORDER != null)
                                {
                                    <span> @((ViewBag.ORDER as TVMLib.dl.Order.OrderAndDetailVM).l_TB_ORDER_DETAIL.Count)</span>
                                }
                                else
                                {
                                    <span> 0</span>
                                }
                            </span>
                        </a>
                        <ul class="dropdown-menu cart-list" role="menu">

                            @if (ViewBag.ORDER != null)
                            {
                                if ((ViewBag.ORDER as TVMLib.dl.Order.OrderAndDetailVM).l_TB_ORDER_DETAIL.Count > 0)
                                {
                                    foreach (var item in (ViewBag.ORDER as TVMLib.dl.Order.OrderAndDetailVM).l_TB_ORDER_DETAIL)
                                    {
                                        <li>
                                            <div class="navbar-cart-item clearfix">
                                                <div class="navbar-cart-img">
                                                    <a href="#"><img src="../@item.l_TB_PRODUCT.PIC1.Substring(item.l_TB_PRODUCT.PIC1.IndexOf("UPLOADFILES"))" alt=""></a>
                                                </div>
                                                <div class="navbar-cart-title">
                                                    <a href="#">@item.l_TB_PRODUCT.NAME</a>
                                                    <span class="cart-amount">NT$ @item.PRICE &nbsp; x &nbsp; @item.UNIT </span><br>
                                                    <strong class="cart-amount">NT$ @(item.SUB_TOTAL)</strong>
                                                </div>
                                            </div>
                                        </li>
                                    }


                                    <li>
                                        <!-- navbar-cart-item -->
                                        <div class="clearfix">
                                            <div class="cart-sub-totle">
                                                <strong>訂單金額小計 : NT$ @((ViewBag.ORDER as TVMLib.dl.Order.OrderAndDetailVM).l_TB_ORDER_DETAIL.Sum(m => m.SUB_TOTAL))</strong>
                                            </div>
                                        </div>
                                    </li>

                                }

                            }

                            @if (ViewBag.ORDER != null)
                            {
                                <li>
                                    <div class="clearfix">
                                        <a href="@Url.Action("Checkout","Product")" class="btn btn-block btn-round btn-font-w">結帳</a>
                                    </div>
                                </li>
                            }


                       

                        </ul>
                    </li>
                    <!-- /CART -->


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">全站搜尋</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <div class="dropdown-search">
                                    <form role="form">
                                        <input type="text" class="form-control" placeholder="請輸入商品關鍵字...">
                                        <button class="search-btn" type="submit"><i class="fa fa-search"></i></button>
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>

        </div>

    </nav>
    <!-- Navigation end -->

    @RenderBody()

    <!-- Footer start -->
    <footer class="footer bg-dark">
        <div class="container">

            <div class="row">

                <div class="col-sm-6">
                    <p style="margin-top:10px" class="copyright font-alt">© @System.DateTime.Now.Year <a href="index.html">KUST Innovative 雄大科技</a>, All Rights Reserved.</p>
                </div>

                <div class="col-sm-6">
                    <div class="footer-social-links" style="font-size:20px !important">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-skype"></i></a>
                    </div>
                </div>

            </div><!-- .row -->

        </div>
    </footer>
    <!-- Footer end -->
    <!-- Scroll-up -->
    <div class="scroll-up">
        <a href="#totop"><i class="fa fa-angle-double-up"></i></a>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/allCustomScript")
        @RenderSection("scripts", required: false)*@

    @if (TempData[TVMLib.common.SealedGlobalPage.RESULT_MESSAGE] != null)
    {
        <div class="alert-box">
            @TempData[TVMLib.common.SealedGlobalPage.RESULT_MESSAGE]

            <style>
                .alert-box {
                    background-color: rgba(79, 92, 89, 0.8);
                    color: #FFF;
                    position: absolute;
                    left: 50%;
                    top: 0;
                    transform: translateX(-50%) translateY(-110%);
                    transition: all .8s;
                    padding: 30px 40px;
                    z-index: 99;
                    border-radius: 10px;
                    font-size: 0.9em;
                    box-shadow: 2px 2px 4px rgba(0,0,0,.15);
                    line-height: 175%;
                }

                    .alert-box.show {
                        top: 150px;
                        transform: translateX(-50%) translateY(0%);
                    }
            </style>

            <script>
                jQuery(function () {
                    $(".alert-box").addClass("show");
                    setTimeout(function () {
                        $('.alert-box').removeClass('show');
                    }, 6000);
                });
            </script>
        </div>
    }


    <script src="~/assets/js/jquery.mb.YTPlayer.min.js"></script>
    <script src="~/assets/js/appear.js"></script>
    <script src="~/assets/js/jquery.simple-text-rotator.min.js"></script>
    <script src="~/assets/js/jqBootstrapValidation.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="~/assets/js/gmaps.js"></script>
    <script src="~/assets/js/isotope.pkgd.min.js"></script>
    <script src="~/assets/js/imagesloaded.pkgd.js"></script>
    <script src="~/assets/js/jquery.flexslider-min.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="~/assets/js/jquery.fitvids.js"></script>
    <script src="~/assets/js/smoothscroll.js"></script>
    <script src="~/assets/js/wow.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/contact.js"></script>
    <script src="~/assets/js/custom.js"></script>
</body>

</html>

prjKUST/Views/Shared/_IndexLayout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KUST Innovative 雄大科技</title>
    <meta name="description" content="">
    <meta name="author" content="">
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <!--favicon-->
    <link rel=icon href="~/assets/favicon/favicon-20200403023240123.ico" sizes="16x16" type="image/png">

    <style>
        @@font-face {
            font-family: 'TaipeiSansTC';
            src: url('/fonts/TaipeiSansTCBeta-Regular.ttf');
            src: url('/fonts/TaipeiSansTCBeta-Bold.ttf');
        }

        body {
            font-family: 'TaipeiSansTC' !important;
        }
    </style>

    <!-- CSS -->
    <link href="~/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/simpletextrotator.css" rel="stylesheet">
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/assets/css/et-line-font.css" rel="stylesheet">
    <link href="~/assets/css/magnific-popup.css" rel="stylesheet">
    <link href="~/assets/css/flexslider.css" rel="stylesheet">
    <link href="~/assets/css/owl.carousel.css" rel="stylesheet">
    <link href="~/assets/css/animate.css" rel="stylesheet">
    <link href="~/assets/css/style.css" rel="stylesheet">
    <script src="~/assets/js/jquery-2.1.3.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>


    @RenderBody()

    @if (TempData[TVMLib.common.SealedGlobalPage.RESULT_MESSAGE] != null)
    {
        <div class="alert-box">
            @TempData[TVMLib.common.SealedGlobalPage.RESULT_MESSAGE]

            <style>
                .alert-box {
                    background-color: rgba(79, 92, 89, 0.8);
                    color: #FFF;
                    position: absolute;
                    left: 50%;
                    top: 0;
                    transform: translateX(-50%) translateY(-110%);
                    transition: all .8s;
                    padding: 30px 40px;
                    z-index: 99;
                    border-radius: 10px;
                    font-size: 0.9em;
                    box-shadow: 2px 2px 4px rgba(0,0,0,.15);
                    line-height: 175%;
                }

                    .alert-box.show {
                        top: 150px;
                        transform: translateX(-50%) translateY(0%);
                    }
            </style>

            <script>
                jQuery(function () {
                    $(".alert-box").addClass("show");
                    setTimeout(function () {
                        $('.alert-box').removeClass('show');
                    }, 6000);
                });
            </script>
        </div>
    }
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/allCustomScript")
        @RenderSection("scripts", required: false)*@
    <!-- Javascript files -->

    <script src="~/assets/js/jquery.mb.YTPlayer.min.js"></script>
    <script src="~/assets/js/appear.js"></script>
    <script src="~/assets/js/jquery.simple-text-rotator.min.js"></script>
    <script src="~/assets/js/jqBootstrapValidation.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="~/assets/js/gmaps.js"></script>
    <script src="~/assets/js/isotope.pkgd.min.js"></script>
    <script src="~/assets/js/imagesloaded.pkgd.js"></script>
    <script src="~/assets/js/jquery.flexslider-min.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="~/assets/js/jquery.fitvids.js"></script>
    <script src="~/assets/js/smoothscroll.js"></script>
    <script src="~/assets/js/wow.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/contact.js"></script>
    <script src="~/assets/js/custom.js"></script>


</body>
</html>